### ISSUE TITLE
(SOKOL) Hardfork 3 checklist

### ISSUE THREAD

**Issue by phahulin** [poanetwork/deployment-playbooks#171]
Instructions: https://github.com/poanetwork/wiki/wiki/HFs-Sokol-2018-09-19#instructions

* Nodes to be updates (**27/27 validator nodes**):

- [x] **Adam Kagy Sokol Validator**
- [x] **Alex Emelyanov | Sokol**
- [x] Artiom C Bootnode
- [x] **Artiom Curencov**
- [x] Bootnode
- [x] _Bootnode-Archive (for backup)_
- [ ] Bootnode - Suzon Crowell
- [x] Bootnode NStoyev
- [x] Bootnode Sokol Las Vegas A
- [x] Bootnode-2
- [x] Bootnode-3
- [x] Bootnode-Azure-1
- [x] Bootnode-Azure-2
- [x] Bootnode-Azure-3
- [x] Bootnode-CentOS
- [x] Bootnode-HB
- [x] Bootnode-Orchestrator-1
- [x] Bootnode-Orchestrator-2
- [x] Bootnode-Orchestrator-3
- [x] Bootnode-OVH
- [x] Bootnode-Solo
- [x] Bootnode-Test
- [x] Bootnode-Test-NDP
- [x] Bootnode-Test-NSG
- [x] Bootnode-Traces
- [x] Bootnode-Traces-2
- [x] Bootnode-Traces-3
- [x] Bootnode-Traces-4
- [x] Bootnode-Traces-5
- [x] Bootnode-Traces-6
- [x] Bootnode-WS
- [x] Dzmitry Miranovich, Sokol Node
- [x] Explorer
- [x] **Henry Vishnevsky**
- [x] **Ian Ferrell Validator**
- [x] **Ilmira Nugumanova**
- [x] Irvin Cardenas Bootnode
- [x] James McGrath Sokol Bootnode
- [x] **James McGrath Sokol Validator**
- [x] Jeff Flowers
- [x] **Jeff Flowers (Val)**
- [x] **Jim O'Regan SOKOL Validator Chicago A**
- [x] **Jim O'Regan SOKOL Validator Chicago B**
- [x] **John D. Storey**
- [x] **John H. LeGassic**
- [ ] Kevin Joy Sokol Bootnode
- [x] **Kristina Yevseyeva Sokol**
- [x] **Lillian Chan**
- [x] **Marat Pekker**
- [x] _**Master of Ceremony** (for backup)_
- [x] **Master of Ceremony (CentOS)**
- [x] **Melanie Marsollier**
- [x] **Michael Milirud**
- [x] MM Azure EastUS Bootnode
- [x] Monitoring
- [x] **Oxana Kunets | NYC-v2**
- [x] **Peter Chen Sokol Validator**
- [x] **Rocco Federico Mancini**
- [x] **Roman Storm**
- [x] **Sherina Hsuan Yang**
- [x] Siarhei Barylau bootnode
- [x] Sokol Bootnode Toronto A
- [x] **Sokol Walter Karshat**
- [x] **Stephen Arsenault**
- [x] **Theresa Cable**

* Submit PR to parity (https://github.com/paritytech/parity-ethereum/pull/9607)

**Comment by mnugumanova** [comment]
Ilmira Nugumanova node is updated

**Comment by 6proof** [comment]
Both Jim O'Regan SOKOL Validator Chicago A and SOKOL Validator Chicago B nodes updated!  No issues.

**Comment by ajkagy** [comment]
"Bootnode Sokol Las Vegas A" and "Adam Kagy Sokol Validator" have been updated and verified.

**Comment by shkron** [comment]
Alex Emelyanov  Sokol Node updated.

**Comment by elillian** [comment]
Lillian Chan Sokol Node updated.

**Comment by henryvishnevsky** [comment]
Henry Vishnevsky sokol validator node updated and verified.

**Comment by Mel-Marsollier** [comment]
Melanie Marsollier Sokol node updated

**Comment by kPatch** [comment]
Irvin Cardenas Bootnode updated.

**Comment by svbarilov** [comment]
Siarhei Barylau updated sokol bootnode

**Comment by micwebnet** [comment]
Updated both boot and validator Sokol nodes, and verified.

**Comment by varasev** [comment]
> NStoyev Bootnode updated

@nstoyev Please update your node to 1.11.8.

**Comment by nstoyev** [comment]
@varasev done!

**Comment by varasev** [comment]
PR in Parity repo: https://github.com/paritytech/parity-ethereum/pull/9607

**Comment by phahulin** [comment]
Done
