### ISSUE TITLE
(Core) HF 2 Checklist

### ISSUE THREAD

**Issue by phahulin** [poanetwork/deployment-playbooks#172]
* Update instructions: https://github.com/poanetwork/wiki/wiki/HFs-Core-2018-10-22#instructions 

* Nodes to be updated (**21/21 validators**)

    - [X] **Adam Kagy**
    - [x] **Alex Emelyanov**
    - [X] Bootnode A
    - [X] Bootnode Adam Kagy
    - [x] Bootnode Atlanta A
    - [x] Bootnode Azure Brazil A
    - [X] Bootnode B
    - [x] Bootnode C
    - [x] Bootnode Chicago A
    - [x] Bootnode Chicago C
    - [x] Bootnode Chicago D
    - [x] Bootnode D
    - [x] Bootnode Dallas A
    - [x] Bootnode Frankfurt
    - [x] Bootnode G
    - [x] Bootnode H
    - [X] Bootnode I
    - [x] Bootnode MoC OVH
    - [x] Bootnode MoC OVH-2
    - [x] Bootnode NStoyev
    - [x] Bootnode Santa Clara
    - [x] Bootnode-Archive
    - [x] Bootnode-Azure-1
    - [x] Bootnode-Azure-2
    - [x] Bootnode-Azure-3
    - [x] Bootnode-Core-B
    - [X] Bootnode-E
    - [X] Bootnode-F
    - [x] Bootnode-HB
    - [x] Bootnode-Traces
    - [x] Bootnode-WS
    - [X] Explorer
    - [x] **Ilmira Nugumanova**
    - [x] **James McGrath**
    - [x] **Jeff Flowers**
    - [x] **Jim O'Regan**
    - [x] **John D. Storey**
    - [x] **John H LeGassic**
    - [x] **Kristina Yevseyeva Core**
    - [x] **Lillian Chan**
    - [X] **Master of Ceremony**
    - [X] **Marat Pekker**
    - [x] **Melanie Marsollier**
    - [x] **Michael Milirud**
    - [x] Monitoring
    - [x] **Oxana Kunets**
    - [x] **Rocco Federico Mancini**
    - [x] **Sherina Hsuan Yang**
    - [x] **Stephen Arsenault**
    - [x] **Sviataslau Vishneuski**
    - [x] Sviataslau Vishneuski Bootnode
    - [x] **Walter Karshat**
    - [x] **Xiaobo (Peter) Chen**

* Parity PR https://github.com/paritytech/parity-ethereum/pull/9724

* Notify exchanges
    - [x] Binance
    - [x] BiBox
    - [ ] CEX Plus
* Notify third parties
    - [x] Infura

**Comment by ajkagy** [comment]
"Adam Kagy" and "Bootnode Adam Kagy" have been updated and verified.

**Comment by henryvishnevsky** [comment]
"Sviataslau Vishneuski" core validator and bootnode updated and verified.

**Comment by shkron** [comment]
"Alex Emelyanov" core validator node has been updated.

**Comment by johndangerstorey** [comment]
John D. Storey validator updated.

**Comment by mnugumanova** [comment]
Ilmira Nugumanova Validator Node has been updated

**Comment by nstoyev** [comment]
Bootnode NStoyev updated

**Comment by ncocchiaro** [comment]
Infura is up to date.

**Comment by johnnynuuma** [comment]
John LeGassic vallidator node updated and verified.

**Comment by ceze** [comment]
Bibox has updated

**Comment by 6proof** [comment]
updated and verified Bootnode Chicago A

**Comment by phahulin** [comment]
Done
